
server:
  port: 8080

spring:
  application:
    name: kbase-backend
  config:
    import: optional:file:./application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5433/kbase_db
    username: kbase_user
    password: ${DB_PASSWORD:kbase_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ayemi597@gmail.com
    password: ${MAIL_PASSWORD:dummy_mail_password_123}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: ${JWT_SECRET:day_la_jwt_secret_gia_danh_cho_moi_truong_dev_dia_phuong}
    expiration-ms: 86400000 # 24 hours
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:sk-dummy-key-for-local-development}

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: kbase-bucket

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
